
name: Code Coverage

on:
  pull_request:
    branches: [ develop ]

jobs:
  execute-unit-code-coverage-report-on-release:
    name: Test coverage report for release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests with coverage flags enabled
        run: |
          sh run_ut.sh --enable-cov
      - name: Caculate the code coverage summary
        run: |
          cd unittest/
          lcov --list coverage.info | grep "Lines\|Total" > /tmp/coverage_summary.txt
          cd -
        
      - name: Update the coverage report to Pull request using actions
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const lcov_result = fs.readFileSync('/tmp/coverage_summary.txt', 'utf8'); 
          
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 
                    '## Code Coverage Summary \n' +
                    ' ' +
                    '```' +
                    lcov_result + 
                    '```'
            });
      - name: Generate the html report
        run: |
          cd unittest/
          genhtml coverage.info --output-directory /tmp/coverage_report
          cd -
      - name: Upload the coverage report to Pull request using actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: /tmp/coverage_report
